---
title: "Coverage assessment using mosdepth"
author: "Sehrish Kanwal"
date: "`r format(Sys.time(), '%a %Y-%b-%d')`"
output:
  html_document:
    keep_md: true
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE) # global setup
```

**Required packages**

```{r, message=FALSE}
library(vcfR)
library(knitr)
library(kableExtra)
```

```{r}
lf <- function(...) {
  data.frame(fname = list.files(...)) %>% 
    knitr::kable(row.names = TRUE)
}
```

**Input data**

As an example of a decent cellaularity sample, I have selected `CCR180136_WH18F001P025 - purity:0.66` (https://trello.com/c/wuChCgKg/209-201624918whp025).

**Mosdepth run command**

Currently, running mosdepth on spartan, using the following command:

```
mosdepth --no-per-base --by $target --quantize 0:10:50:500: $sample $bam

--no-per-base     dont output per-base depth. skipping this output will speed execution
                  substantially. prefer quantized or thresholded values if possible. 
                  
--by              the $target file - currently using the hotspot regions.

--quantize        allows splitting coverage into bins and merging adjacent regions 
                  that fall into the same bin even if they have different exact coverage values.
```

The location of run directory on spartan is `/data/cephfs/punim0010/projects/Kanwal/Kanwal_mosdepth/samplename`.

**Mosdepth output**

```{r, message=FALSE}
mosdepth <- "/Users/kanwals/Documents/UMCCR/data/mosdepth"
mosdepth_decentcell <- file.path(mosdepth, "CCR180136_WH18F001P025")
#call lf function to list files in the directory
lf(mosdepth_decentcell)

#read regions.bed file - first grep the appropriate bed file from folder and then create a path for that name
regions_bed_name <- list.files(mosdepth_decentcell)[grep(".regions.bed$",list.files(mosdepth_decentcell))]
regions_bed_name <- file.path(mosdepth_decentcell, regions_bed_name)
regions_bed <- as.data.frame(read.table(regions_bed_name, header = FALSE, sep = "\t", stringsAsFactors = FALSE))
#read hotspots file - to include the column that shows the change from ref. nucleaotide in the regions.bed file
hotspots <- as.data.frame(read.table("~/Documents/UMCCR/data/mosdepth/hotspot.edited.bed", header = FALSE, sep = "\t", stringsAsFactors = FALSE))
#merge region_bed file with hotspots column that has info about the possible nucleotide change. Also avoid adding an additional Row.names column by setting it to NULL
regions_bed_hotspot <- transform(merge(regions_bed, hotspots$V5, by = "row.names", sort = FALSE), Row.names=NULL) %>%
  select(V1, V2, V3, V4, y, V5)
#add column names  
colnames(regions_bed_hotspot) <- c("chrom","chromStart","chromEnd", "Ref", "Alt", "Cov")
```



